version: '2'
services:
  postgres-db:
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgres/data
      POSTGRES_DB: sample
    volumes:
      - pg-data:/var/lib/postgres/data
    ports:
      - 5434:5434/tcp
volumes:
  pg-data: # docker volume create pg-data
    external: true